---
title: "NonParametric & Counting Statistics"
author: "YOUR NAME HERE"
format: 
  html:
    toc: false
    code-tools: true 
---


This assignment covers the materials found in the lecure on Counting Statistics & Other Non-Parametric Approaches.  As is common, answer this using a Quarto document and push it to your repository and turn in the url.


## Data For the Questions

The data for these questions include the following, which are found in the data sub folder.  
- Graduate School GRE/GPA Data.       
- Turbidity Data.   
- Dogwood Seed Yield Data. 

## Questions

For each of the following questions, please provide your analysis and an interpretation (e.g., written as you would in a scientific publication).  If it helps to describe your result, feel free to add tables or figures to help make your case. For every case, describe why you chose the particular analysis you did and demonstrate the reasons from the data.


1. The FDA has suggested a change in a medication that has been shown to have detrimental side effects in half of the patients.  A clinical trial was conducted with nineteen patients and only three reported the aforementioned side-effect.  Did the change make a significant difference?  
2. Two different environmental remediation treatments are evaluated for the impacts on turbidity (measured using the Nephelometric Turbidity Unit or NTU).  For regulatory reasons, turbidity is binned into four groups based upon NTU; 0-15 ntu, 16-22 ntu, 23-30 ntu, and 31+ ntu.  Do both treatments have the same impact on turbidity?  Explain.
3. A dozen graduate students tried to determine if there was a relationship between their undergraduate GPA and their scores on the Graduate Records Examination.  Look at these data and determine the extent to which they are related.  Explain.
4. You are looking at fruit yield on dogwood.  You designed an experiment with four different treatments and measured the total yield in germinated seeds.  Are there differences in yield?  Explain.


